### ISSUE TITLE
Extra templating variables in targets

### ISSUE THREAD

**Issue by langston-barrett** [asteris-llc/hammer#30]
When `template: true` is provided for a target, there should be a way to create a dictionary of string variables that can be available to that templating process. 

``` yaml
targets:
  - src: ../foo/bar.json.tmpl
    dest: /etc/baz.json
    template: true
    vars:
      var1: value1
      var2: value2
```
