### ISSUE TITLE
include script from filesystem instead of inline

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/hammer#8]
Syntax maybe like:

``` yaml
scripts:
  before-install: |
    {{include "before-install.sh"}}
```
